TABLE_CONFIG = [
    {
        "name": "customers",
        "file": "customers.csv",
        "table": "raw_customers",
        "pk": "customer_id",
        "required_columns": [
            "customer_id",
            "customer_unique_id",
            "customer_zip_code_prefix",
            "customer_city",
            "customer_state",
        ],
        "enabled": True,
    },
    {
        "name": "orders",
        "file": "orders.csv",
        "table": "raw_orders",
        "pk": "order_id",
        "required_columns": [
            "order_id",
            "customer_id",
            "order_status",
            "order_purchase_timestamp",
        ],
        "enabled": True,
    },
    {
        "name": "order_items",
        "file": "order_items.csv",
        "table": "raw_order_items",
        "pk": ["order_id", "order_item_id"],
        "required_columns": [
            "order_id",
            "order_item_id",
            "product_id",
            "seller_id",
            "price",
            "freight_value",
        ],
        "enabled": True,
    },
    {
        "name": "products",
        "file": "products.csv",
        "table": "raw_products",
        "pk": "product_id",
        "required_columns": [
            "product_id",
            "product_category_name",
        ],
        "enabled": True,
    },
    {
        "name": "payments",
        "file": "payments.csv",
        "table": "raw_payments",
        "pk": ["order_id", "payment_sequential"],
        "required_columns": [
            "order_id",
            "payment_sequential",
            "payment_type",
            "payment_value",
        ],
        "enabled": True,
    },
    {
        "name": "shipments",
        "file": "shipments.csv",
        "table": "raw_shipments",
        "pk": "order_id",
        "required_columns": [
            "order_id",
            "delivered_customer_date",
            "estimated_delivery_date",
        ],
        "enabled": True,
    },
]