version: 2

models:
  - name: mart_daily_revenue
    description: "Data mart doanh thu theo ngày phục vụ báo cáo nghiệp vụ."
    columns:
      - name: order_date
        tests:
          - not_null
          - unique

      - name: total_orders
        tests:
          - not_null

      - name: gross_order_value
        tests:
          - not_null

      - name: average_gross_order_value
        tests:
          - not_null

  - name: mart_product_performance
    description: "Data mart hiệu quả sản phẩm theo sản phẩm và danh mục."
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

      - name: product_category_name
        tests:
          - not_null

      - name: total_quantity
        tests:
          - not_null

      - name: total_orders
        tests:
          - not_null

      - name: total_item_revenue
        tests:
          - not_null

      - name: total_freight_value
        tests:
          - not_null

      - name: gross_order_value
        tests:
          - not_null

  - name: mart_delivery_performance
    description: "Data mart hiệu quả giao hàng ở grain đơn hàng."
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: is_late_delivery
        tests:
          - not_null
